<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ObjectDataSource4.aspx.cs" Inherits="RepeatedValue.ObjectDataSource4" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:ObjectDataSource ID="sourceEmployees" runat="server"
	        TypeName="RepeatedValue.EmployeeDB"
	        DataObjectTypeName="RepeatedValue.EmployeeDetails"
	        SelectMethod="GetEmployees"
	        InsertMethod="InsertEmployee"
	        DeleteMethod="DeleteEmployee"
	        OnInserted="sourceEmployees_Inserted">
        </asp:ObjectDataSource>

        <asp:DetailsView ID="detailsInsertEmployee" runat="server" DataSourceID="sourceEmployees" 
            DefaultMode="Insert" AutoGenerateInsertButton="True" />

        <asp:Label ID="lblConfirmation" Font-Name="Verdana" Font-Size="Small" runat="server" 
            EnableViewState="false"></asp:Label>
        <br /><br />

        <asp:GridView ID="gridEmployeeList" runat="server" DataSourceID="sourceEmployees"
            DataKeyNames="EmployeeID" AutoGenerateDeleteButton="true" />

    </div>
    </form>
</body>
</html>
